# Basics


## Lists[]
**mutable, ordered sequence of elements.**
- Mix of data types.
- Are ordered - can lookup elements by index.
- Are mutable - can be changed.

### List Comprehensions - (do.. for)

In [ ]:
names = ['dumbledore', 'beeblebrox', 'skywalker', 'hermione', 'leia']
capitalized_names = []
for name in names:
    capitalized_names.append(name.title())

# equals (do.. for)
capitalized_names = [name.title() for name in names]
capitalized_names

['Dumbledore', 'Beeblebrox', 'Skywalker', 'Hermione', 'Leia']

### adding conditionals (do.. for.. if)

In [ ]:
squares = [x**2 for x in range(9) if x % 2 == 0]
# to add else statements, move the conditionals to the beginning
squares = [x**2 if x % 2 == 0 else x + 3 for x in range(9)]

### examples

In [ ]:
# example
names = ["Rick S", "Morty Smith", "Summer Smith", "Jerry Smith", "Beth Smith"]
first_names = [name.split(' ')[0] for name in names]
print(first_names)
# ['Rick', 'Morty', 'Summer', 'Jerry', 'Beth']

# example
multiples_3 = [i*3 for i in range(1,21)]
print(multiples_3)
# [3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]

# example
scores = {
             "Rick": 70,
             "Morty Smith": 35,
             "Summer Smith": 82,
             "Jerry Smith": 23,
             "Beth Smith": 98
          }
passed = [name for name, score in scores.items() if score>=65]
print(passed)
# ['Rick', 'Summer Smith', 'Beth Smith']

['Rick', 'Morty', 'Summer', 'Jerry', 'Beth']
[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60]
['Rick', 'Summer Smith', 'Beth Smith']


### Lambda Functions

In [ ]:
# Lambda Functions - lambda (arg1, arg2): do_a_thing_and_return_it
multiply = lambda x, y: x * y

# Equivalent of:
def multiply(x, y):
    return x * y

# Can call both of the above like:
multiply(4, 7)

28

### map() - apply lambda function to a list

In [ ]:
# example of using map() to apply lambda function to a list
numbers = [
              [34, 63, 88, 71, 29],
              [90, 78, 51, 27, 45],
              [63, 37, 85, 46, 22],
              [51, 22, 34, 11, 18]
           ]
mean = lambda num_list: sum(num_list)/len(num_list)
averages = list(map(mean, numbers))
# or
averages = list(map(lambda num_list: sum(num_list)/len(num_list), numbers))
print(averages)
# [57.0, 58.2, 50.6, 27.2]

[57.0, 58.2, 50.6, 27.2]


### filter() - apply lambda function to a list

In [ ]:
# example of using filter() to apply lambda function to a list
cities = ["New York City", "Los Angeles", "Chicago", "Mountain View", "Denver", "Boston"]
is_short = lambda name: len(name) < 10
short_cities = list(filter(is_short, cities))
# or
short_cities = list(filter(lambda name: len(name) < 10, cities))
print(short_cities)

['Chicago', 'Denver', 'Boston']


### Generators

In [ ]:
# Generators
def my_range(x):
    i = 0
    while i < x:
        yield i
        i += 1
# since this returns an iterator, we can convert it to a list
# or iterate through it in a loop to view its contents
for x in my_range(5):
    print(x)
'''
0
1
2
3
4
'''

# You can create a generator in the same way you'd normally write a list comprehension, except with
# parentheses instead of square brackets.
# this list comprehension produces a list of squares
sq_list = [x**2 for x in range(10)]
# this generator produces an iterator of squares
sq_iterator = (x**2 for x in range(10))

# example
# generator function that works like the built-in function enumerate
lessons = ["Why Python Programming", "Data Types and Operators", "Control Flow", "Functions", "Scripting"]
def my_enumerate(iterable, start=0):
    i = start
    for element in iterable:
        yield i, element
        i = i + 1
for i, lesson in my_enumerate(lessons, 1):
    print("Lesson {}: {}".format(i, lesson))
'''
Lesson 1: Why Python Programming
Lesson 2: Data Types and Operators
Lesson 3: Control Flow
Lesson 4: Functions
Lesson 5: Scripting
'''

# example
# If you have an iterable that is too large to fit in memory in full
# (e.g., when dealing with large files), being able to take and use
# chunks of it at a time can be very valuable.
# Implementing a generator function, chunker, that takes in an
# iterable and yields a chunk of a specified size at a time.
def chunker(iterable, size):
    for i in range(0, len(iterable), size):
        yield iterable[i:i + size]
for chunk in chunker(range(25), 4):
    print(list(chunk))

0
1
2
3
4
Lesson 1: Why Python Programming
Lesson 2: Data Types and Operators
Lesson 3: Control Flow
Lesson 4: Functions
Lesson 5: Scripting
[0, 1, 2, 3]
[4, 5, 6, 7]
[8, 9, 10, 11]
[12, 13, 14, 15]
[16, 17, 18, 19]
[20, 21, 22, 23]
[24]


### create list

In [ ]:
list_of_random_things = [1, 3.4, 'a string', True]

### access list elements

In [ ]:
list_of_random_things[0];
list_of_random_things[-1]; #last element
list_of_random_things[len(list_of_random_things) - 1]; #last element

### slicing [,)

In [ ]:
list_of_random_things[1:3] # returns [3.4, 'a string']
list_of_random_things[:2] # returns [1, 3.4]
list_of_random_things[1:] # returns all of the elements to the end of the list [3.4, 'a string', True]

[3.4, 'a string', True]

### in, not in

In [ ]:
# in, not in
'this' in 'this is a string' # True
'in' in 'this is a string' # True
'isa' in 'this is a string' # False
5 not in [1, 2, 3, 4, 6] # True
5 in [1, 2, 3, 4, 6] # False

False

### Mutable and ordered

In [ ]:
# Mutable and ordered
my_lst = [1, 2, 3, 4, 5]
my_lst[0] = 0
print(my_lst)

[0, 2, 3, 4, 5]


### length of list

In [ ]:
# length of list
len(list_of_random_things)

4

### smallest and greatest element in list

In [ ]:
# returns the smallest element of the list
min(list_of_random_things)

# returns the greatest element of the list. This works because the the max function is defined in terms of the greater than comparison operator. The max function is undefined for lists that contain elements from different, incomparable types.
max(list_of_random_things)

TypeError: '<' not supported between instances of 'str' and 'int'

### sort list

In [ ]:
# returns a copy of a list in order from smallest to largest,
# leaving the list unchanged.
sorted(list_of_random_things)

TypeError: '<' not supported between instances of 'str' and 'float'

### join()

In [ ]:
# join() returns a string consisting of the list elements joined by a separator string.
# Takes only a list of strings as an argument
name = "-".join(["Grace", "Kelly"])
print(name) # Grace-Kelly

Grace-Kelly


### Creating a new list

In [ ]:
cities = ['new york city', 'mountain view', 'chicago', 'los angeles']
capitalized_cities = []
for city in cities:
    capitalized_cities.append(city.title())

### Adding an element to the end of a list - append()

In [ ]:
letters = ['a', 'b', 'c', 'd']
letters.append('z')
print(letters) # ['a', 'b', 'c', 'd', 'z']
# Note: letters[i] = 'z'; wouldn't work, use append()

['a', 'b', 'c', 'd', 'z']


### Modifying a new list

In [ ]:
cities = ['new york city', 'mountain view', 'chicago', 'los angeles']
for index in range(len(cities)):
    cities[index] = cities[index].title()

### Print a formatted string from parameters in list

In [ ]:
items = ['first string', 'second string']
html_str = "<ul>\n"
for item in items:
    html_str += "<li>{}</li>\n".format(item)
html_str += "</ul>"
print(html_str)

<ul>
<li>first string</li>
<li>second string</li>
</ul>


### Convert an iterable (tuple, string, set, dictionary) to a list - list()

In [ ]:
# vowel string
vowelString = 'aeiou'
print(list(vowelString))

# vowel tuple
vowelTuple = ('a', 'e', 'i', 'o', 'u')
print(list(vowelTuple))

# vowel list
vowelList = ['a', 'e', 'i', 'o', 'u']
print(list(vowelList))

# All Print: ['a', 'e', 'i', 'o', 'u']

['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']
['a', 'e', 'i', 'o', 'u']


## Tuples()
**immutable ordered sequences of elements.**
- They are often used to store related pieces of information. The parentheses are optional when defining tuples.
- Are ordered - can lookup elements by index.
- Are immutable - can not be changed. You can't add and remove items from tuples, or sort them in place.

### create tuple

In [ ]:
location = (13.4125, 103.866667)

### access tuple

In [ ]:
print("Latitude:", location[0])
print("Longitude:", location[1])

Latitude: 13.4125
Longitude: 103.866667


### tuple packing

In [ ]:
# can also be used to assign multiple variables in a compact way
dimensions = 52, 40, 100

### tuple unpacking

In [ ]:
# tuple unpacking
length, width, height = dimensions
print("The dimensions are {} x {} x {}".format(length, width, height))

The dimensions are 52 x 40 x 100


## Sets{}
**mutable, unordered collections of unique elements.**
- Are unordered - can not lookup elements by index.
- Are mutable - can be changed.
- Sets support the **in** operator the same as lists do.
- One application of a set is to quickly remove duplicates from a list.
- You cannot have the same item twice and you cannot sort sets. For these two properties a list would be more appropriate.
- You can add elements to sets using the **add()** method, and remove elements using the **pop()** method, similar to lists. Although, when you pop an element from a set, a random element is removed. Remember that sets, unlike lists, are unordered so there is no "last element".
- Other operations you can perform with sets include those of mathematical sets. Methods like union, intersection, and difference are easy to perform with sets, and are much faster than such operators with other containers.

### create sets

In [ ]:
numbers = [1, 2, 6, 3, 1, 1, 6]
unique_nums = set(numbers)
print(unique_nums) # {1, 2, 3, 6}

{1, 2, 3, 6}


In [ ]:
fruit = {"apple", "banana", "orange", "grapefruit"}

### check for element

In [ ]:
print("watermelon" in fruit)

False


### add an element

In [ ]:
fruit.add("watermelon")
print(fruit)

{'apple', 'grapefruit', 'orange', 'watermelon', 'banana'}


### remove a random element

In [ ]:
print(fruit.pop())
print(fruit)

apple
{'grapefruit', 'orange', 'watermelon', 'banana'}


## Dicts{}
**mutable data type that stores mappings of unique keys to values.**
- Are ordered - can lookup elements by key.
- Are mutable - can be changed.
- Dictionaries can have *keys of any immutable type*, like integers or tuples, not just strings. It's not even necessary for every key to have the same type!
- We can look up values or insert new values in the dictionary using square brackets that enclose the key.

### create dict

In [ ]:
elements = {"hydrogen": 1, "helium": 2, "carbon": 6}

### accessing an element's value

In [ ]:
print(elements["helium"])

2


### adding elements

In [ ]:
elements["lithium"] = 3 

### Iterating through a dictionary

In [ ]:
# Just keys
for key in cast:
    print(key)
# Keys and values
for key, value in cast.items():
    print("Actor: {}    Role: {}".format(key, value))

NameError: name 'cast' is not defined

### check whether a value is in a dictionary

In [ ]:
# check whether a value is in a dictionary, the same way we check whether a value is in a list or set with the in keyword.
print("carbon" in elements) # True

True


### get() looks up values in a dictionary

In [ ]:
# get() looks up values in a dictionary, but unlike square brackets, get returns None (or a default value of your choice) if the key isn't found.
# If you expect lookups to sometimes fail, get might be a better tool than normal square bracket lookups.
print(elements.get("dilithium")) # None
print(elements.get('kryptonite', 'There\'s no such element!'))
# "There's no such element!"

None
There's no such element!


### Identity Operators

In [ ]:
n = elements.get("dilithium")
print(n is None) # True
print(n is not None) # False

True
False


### Equality (==) and identity (is)

In [ ]:
a = [1, 2, 3]
b = a
c = [1, 2, 3]
print(a == b) # True
print(a is b) # True
print(a == c) # True
print(a is c) # False
# List a and list b are equal and identical.
# List c is equal to a (and b for that matter) since they have the same contents. But a and c (and b for that matter, again) point to two different objects, i.e., they aren't identical objects.
# That is the difference between checking for equality vs. identity.

True
True
True
False


### Compound Data Structures

In [ ]:
elements = {"hydrogen": {"number": 1,
                         "weight": 1.00794,
                         "symbol": "H"},
              "helium": {"number": 2,
                         "weight": 4.002602,
                         "symbol": "He"}}
helium = elements["helium"]  # get the helium dictionary
hydrogen_weight = elements["hydrogen"]["weight"]  # get hydrogen's weight
oxygen = {"number":8,"weight":15.999,"symbol":"O"}  # create a new oxygen dictionary 
elements["oxygen"] = oxygen  # assign 'oxygen' as a key to the elements dictionary
print('elements = ', elements)

elements =  {'hydrogen': {'number': 1, 'weight': 1.00794, 'symbol': 'H'}, 'helium': {'number': 2, 'weight': 4.002602, 'symbol': 'He'}, 'oxygen': {'number': 8, 'weight': 15.999, 'symbol': 'O'}}


### Dict frequency counter

In [ ]:
words =  ['great', 'expectations','the', 'adventures', 'of', 'sherlock','holmes','the','great','gasby','hamlet','adventures','of','huckleberry','fin'];
word_counter = {}
for word in words:
    word_counter[word] = word_counter.get(word,0)+1;
print(word_counter);
# Prints {'fin': 1, 'huckleberry': 1, 'hamlet': 1, 'holmes': 1, 'adventures': 2, 'sherlock': 1, 'expectations': 1, 'great': 2, 'the': 2, 'of': 2, 'gasby': 1}

{'great': 2, 'expectations': 1, 'the': 2, 'adventures': 2, 'of': 2, 'sherlock': 1, 'holmes': 1, 'gasby': 1, 'hamlet': 1, 'huckleberry': 1, 'fin': 1}


# Numpy



- NumPy provides Python with an extensive math library capable of performing numerical computations effectively and efficiently.
    - Even though Python lists are great on their own, NumPy has a number of key features that give it great advantages over Python lists. One such feature is speed. When performing operations on large arrays NumPy can often perform several orders of magnitude faster than Python lists. This speed comes from the nature of NumPy arrays being memory-efficient and from optimized algorithms used by NumPy for doing arithmetic, statistical, and linear algebra operations.
    - Another great feature of NumPy is that it has multidimensional array data structures that can represent vectors and matrices. Another great advantage of NumPy over Python lists is that NumPy has a large number of optimized built-in mathematical functions. These functions allow you to do a variety of complex mathematical computations very fast and with very little code (avoiding the use of complicated loops) making your programs more readable and easier to understand.
- At the core of NumPy is the **ndarray**, where nd stands for n-dimensional.
    - An ndarray is a multidimensional array of elements **all of the same type**.
    - Unlike Python lists, all the elements of an ndarray must be of the same type. If you provide the np.array() function with a Python list that has both integers and strings, NumPy will interpret all elements as strings.
    - When we create an ndarray with both floats and integers, NumPy assigns its elements a float64 dtype. This is called **upcasting**. Since all the elements of an ndarray must be of the same type, in this case NumPy upcasts the integers in z to floats in order to avoid losing precision in numerical computations.
- We refer to 1D arrays as rank 1 arrays. In general N-Dimensional arrays have rank N. Therefore, we refer to a 2D array as a rank 2 array.

In [ ]:
import numpy as np

## Create ndarray

In [ ]:
# Create a 1D ndarray that contains only integers
x = np.array([1, 2, 3, 4, 5])
print('x = ', x) # x = [1 2 3 4 5]
print('x has dimensions:', x.shape) # x has dimensions: (5,)
print('The elements in x are of type:', x.dtype) # The elements in x are of type: int64

# Create a rank 2 ndarray that only contains integers
Y = np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print('Y has dimensions:', Y.shape) # Y has dimensions: (4, 3)
print('Y has a total of', Y.size, 'elements') # Y has a total of 12 elements
print('Y is an object of type:', type(Y)) # Y is an object of type: class 'numpy.ndarray'
print('The elements in Y are of type:', Y.dtype) # The elements in Y are of type: int64

x =  [1 2 3 4 5]
x has dimensions: (5,)
The elements in x are of type: int64
Y has dimensions: (4, 3)
Y has a total of 12 elements
Y is an object of type: <class 'numpy.ndarray'>
The elements in Y are of type: int64


## Create ndarray with dtype

In [ ]:
# Specify the dtype when creating the ndarray
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype = np.int64)

## Save and load

In [ ]:
# Save the array into a file
np.save('my_array', x)

# Load the saved array from current directory
y = np.load('my_array.npy')

## Zeros

In [ ]:
# Create ndarray using built-in functions
# 3 x 4 ndarray full of zeros
# np.zeros(shape)
X = np.zeros((3,4))

## Ones

In [ ]:
# a 3 x 2 ndarray full of ones
# np.ones(shape)
X = np.ones((3,2))

## Full

In [ ]:
# 2 x 3 ndarray full of fives
# np.full(shape, constant value)
X = np.full((2,3), 5)

## Identity Matrix

In [ ]:
# Identity Matrix
# Since all Identity Matrices are square, the np.eye() function only takes a single integer as an argument
# 5 x 5 Identity matrix
X = np.eye(5)

## Diagonal Matrix

In [ ]:
# Diagonal Matrix
# 4 x 4 diagonal matrix that contains the numbers 10,20,30, and 50 on its main diagonal
X = np.diag([10,20,30,50])

## Arange

In [ ]:
# Arange
# rank 1 ndarray that has sequential integers from 0 to 9
# x = [0 1 2 3 4 5 6 7 8 9]
x = np.arange(10)

# rank 1 ndarray that has sequential integers from 4 to 9
# [start, stop)
# x = [4 5 6 7 8 9]
x = np.arange(4,10)

# rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3.
# np.arange(start,stop,step)
# x = [ 1 4 7 10 13]
x = np.arange(1,14,3)

## Linspace

In [ ]:
# Linspace
# Even though the np.arange() function allows for non-integer steps,
# such as 0.3, the output is usually inconsistent, due to the finite
# floating point precision. For this reason, in the cases where
# non-integer steps are required, it is usually better to use linspace()
# becayse np.linspace() uses the number of elements we want in a
# particular interval, instead of the step between values.
# linspace returns N evenly spaced numbers over the closed interval [start, stop]
# np.linspace(start, stop, N)
# x = [ 0. 2.77777778 5.55555556 8.33333333 11.11111111 13.88888889 16.66666667 19.44444444 22.22222222 25. ]
x = np.linspace(0,25,10)

## Reshape

In [ ]:
# Reshape
# np.reshape(ndarray, new_shape)
# converts the given ndarray into the specified new_shape
x = np.arange(20)
x = np.reshape(x, (4,5))
# or
x = np.arange(20).reshape(4, 5) # does the same thing as above
# and the same thing with with linshape
y = np.linspace(0,50,10, endpoint=False).reshape(5,2)
# One great feature about NumPy, is that some functions can also be
# applied as methods. This allows us to apply different functions in
# sequence in just one line of code

## Slicing

In [ ]:
# Slicing
# ndarray[start:end]
# ndarray[start:]
# ndarray[:end]
# ndarray[<start>:<stop>:<step>]

# In methods one and three, the end index is excluded [,)
X = np.arange(20).reshape(4, 5)

# select all the elements that are in the 2nd through 4th rows and in the 3rd to 5th columns
Z = X[1:4,2:5]
# or
Z = X[1:,2:5]

# elements = a_list[<start>:<stop>:<step>]
# select all the elements in the 3rd row
v = X[2,:] # v = [10 11 12 13 14]
# select all the elements in the 3rd column
q = X[:,2] # q = [ 2 7 12 17]
# select all the elements in the 3rd column but return a rank 2 ndarray
R = X[:,2:3]
'''
[[ 2]
 [ 7]
 [12]
 [17]]
'''
# Note: Slicing creates a view, not a copy
# when we make assignments, such as: Z = X[1:4,2:5]
# the slice of the original array X is not copied in the variable Z.
# Rather, X and Z are now just two different names for the same ndarray.
# We say that slicing only creates a view of the original array.
# This means if we make changes to Z, X changes as well.

'\n[[ 2]\n [ 7]\n [12]\n [17]]\n'

## Random

In [ ]:
# Random
# 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0).
# np.random.random(shape)
X = np.random.random((3,3))
# np.random.randint(start, stop, size = shape)
# [start, stop)
X = np.random.randint(4,15,size=(3,2))

# create ndarrays with random numbers that satisfy certain statistical properties
# 1000 x 1000 ndarray of random floats drawn from normal (Gaussian)
# distribution with a mean of zero and a standard deviation of 0.1.
# np.random.normal(mean, standard deviation, size=shape)
X = np.random.normal(0, 0.1, size=(1000,1000))

## Mutability

In [ ]:
# Mutability
# Change ndarray
x[3] = 20
X[0,0] = 20

## Delete

In [ ]:
# Delete
# np.delete(ndarray, elements, axis)
x = np.array([1, 2, 3, 4, 5])
# delete the first and fifth element of x
x = np.delete(x, [0,4])

Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
# delete the first row of Y
w = np.delete(Y, 0, axis=0)
# delete the first and last column of Y
v = np.delete(Y, [0,2], axis=1)

## Append

In [ ]:
# Append
# np.append(ndarray, elements, axis)
# append the integer 6 to x
x = np.append(x, 6)
# append the integer 7 and 8 to x
x = np.append(x, [7,8])
# append a new row containing 7,8,9 to y
v = np.append(Y, [[10,11,12]], axis=0)
# append a new column containing 9 and 10 to y
q = np.append(Y,[[13],[14],[15]], axis=1)

## Insert

In [ ]:
# Insert
# np.insert(ndarray, index, elements, axis)
# inserts the given list of elements to ndarray right before
# the given index along the specified axis
x = np.array([1, 2, 5, 6, 7])
Y = np.array([[1,2,3],[7,8,9]])
# insert the integer 3 and 4 between 2 and 5 in x. 
x = np.insert(x,2,[3,4])
# insert a row between the first and last row of Y
w = np.insert(Y,1,[4,5,6],axis=0)
# insert a column full of 5s between the first and second column of Y
v = np.insert(Y,1,5, axis=1)

## Stacking

In [ ]:
# Stacking
# NumPy also allows us to stack ndarrays on top of each other,
# or to stack them side by side. The stacking is done using either
# the np.vstack() function for vertical stacking, or the np.hstack()
# function for horizontal stacking. It is important to note that in
# order to stack ndarrays, the shape of the ndarrays must match.
x = np.array([1,2])
Y = np.array([[3,4],[5,6]])
z = np.vstack((x,Y)) # [[1,2], [3,4], [5,6]]
w = np.hstack((Y,x.reshape(2,1))) # [[3,4,1], [5,6,2]]

## Copy

In [ ]:
# Copy
# if we want to create a new ndarray that contains a copy of the
# values in the slice we need to use the np.copy()
# create a copy of the slice using the np.copy() function
Z = np.copy(X[1:4,2:5])
#  create a copy of the slice using the copy as a method
W = X[1:4,2:5].copy()

## Extract elements along the diagonal

In [ ]:
# Extract elements along the diagonal
d0 = np.diag(X)
# As default is k=0, which refers to the main diagonal.
# Values of k > 0 are used to select elements in diagonals above
# the main diagonal, and values of k < 0 are used to select elements
# in diagonals below the main diagonal.
d1 = np.diag(X, k=1)
d2 = np.diag(X, k=-1)

## Find Unique Elements

In [ ]:
# Find Unique Elements in ndarray
u = np.unique(X)

## Boolean Indexing

In [ ]:
# Boolean Indexing
X = np.arange(25).reshape(5, 5)
print('The elements in X that are greater than 10:', X[X > 10])
print('The elements in X that less than or equal to 7:', X[X <= 7])
print('The elements in X that are between 10 and 17:', X[(X > 10) & (X < 17)])

# use Boolean indexing to assign the elements that
# are between 10 and 17 the value of -1
X[(X > 10) & (X < 17)] = -1

The elements in X that are greater than 10: [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
The elements in X that less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in X that are between 10 and 17: [11 12 13 14 15 16]


## Set Operations

In [ ]:
# Set Operations
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])
print('The elements that are both in x and y:', np.intersect1d(x,y))
print('The elements that are in x that are not in y:', np.setdiff1d(x,y))
print('All the elements of x and y:',np.union1d(x,y))

The elements that are both in x and y: [2 4]
The elements that are in x that are not in y: [1 3 5]
All the elements of x and y: [1 2 3 4 5 6 7 8]


## Sorting

In [ ]:
# Sorting
# When used as a function, it doesn't change the original ndarray
s = np.sort(x)
# When used as a method, the original array will be sorted
x.sort()

# sort x but only keep the unique elements in x
s = np.sort(np.unique(x))

# sort the columns of X
s = np.sort(X, axis = 0)

# sort the rows of X
s = np.sort(X, axis = 1)

## Math Functions

In [ ]:
# NumPy allows element-wise operations on ndarrays as well as
# matrix operations. In order to do element-wise operations,
# NumPy sometimes uses something called Broadcasting.
# Broadcasting is the term used to describe how NumPy handles
# element-wise arithmetic operations with ndarrays of different shapes.
# For example, broadcasting is used implicitly when doing arithmetic
# operations between scalars and ndarrays.
x = np.array([1,2,3,4])
y = np.array([5.5,6.5,7.5,8.5])
np.add(x,y)
np.subtract(x,y)
np.multiply(x,y)
np.divide(x,y)

# in order to do these operations the shapes of the ndarrays
# being operated on, must have the same shape or be broadcastable
X = np.array([1,2,3,4]).reshape(2,2)
Y = np.array([5.5,6.5,7.5,8.5]).reshape(2,2)
np.add(X,Y)
np.subtract(X,Y)
np.multiply(X,Y)
np.divide(X,Y)

# apply mathematical functions to all elements of an ndarray at once
np.exp(x)
np.sqrt(x)
np.power(x,2)

array([ 1,  4,  9, 16])

## Statistical Functions

In [ ]:
# Statistical Functions
print('Average of all elements in X:', X.mean())
print('Average of all elements in the columns of X:', X.mean(axis=0))
print('Average of all elements in the rows of X:', X.mean(axis=1))
print()
print('Sum of all elements in X:', X.sum())
print('Standard Deviation of all elements in X:', X.std())
print('Median of all elements in X:', np.median(X))
print('Maximum value of all elements in X:', X.max())
print('Minimum value of all elements in X:', X.min())

Average of all elements in X: 2.5
Average of all elements in the columns of X: [2. 3.]
Average of all elements in the rows of X: [1.5 3.5]

Sum of all elements in X: 10
Standard Deviation of all elements in X: 1.118033988749895
Median of all elements in X: 2.5
Maximum value of all elements in X: 4
Minimum value of all elements in X: 1


## Broadcasting

In [ ]:
# Broadcasting
# NumPy is working behind the scenes to broadcast 3 along the ndarray
# so that they have the same shape. This allows us to add 3 to each
# element of X with just one line of code.
print(4*X)
print(4+X)
print(4-X)
print(4/X)
# NumPy is able to add 1 x 3 and 3 x 1 ndarrays to 3 x 3 ndarrays
# by broadcasting the smaller ndarrays along the big ndarray so that
# they have compatible shapes. In general, NumPy can do this provided
# that the smaller ndarray can be expanded to the shape of the larger
# ndarray in such a way that the resulting broadcast is unambiguous.
x = np.array([1,2,3])
Y = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z = np.array([1,2,3]).reshape(3,1)
print(x + Y)
print(Z + Y)

[[ 4  8]
 [12 16]]
[[5 6]
 [7 8]]
[[3 2]
 [1 0]]
[[4.         2.        ]
 [1.33333333 1.        ]]
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
